### ISSUE TITLE
Trouble building statically.

### ISSUE THREAD

**Issue by TrevorHansen** [msoos/cryptominisat#337]
I'm trying to build CMS statically, but I'm getting a linking error. I've not used Cmake much, so there's a good chance I'm missing something obvious.

Thanks, Trev.
[log.txt](https://github.com/msoos/cryptominisat/files/260632/log.txt)

**Comment by msoos** [comment]
Thanks! Can you please paste the output of the "cmake" command as well? (after `rm -rf build`) Also, can you please tell me what distribution you are running (e.g. Ubuntu 14.04)? Thanks!

**Comment by msoos** [comment]
Oh, and where c++ points to (`which c++` then `ls -lah [wherever c++ is]`) and the version of the compiler it points to. e.g. `gcc --version` or `clang --version`. Thanks!

**Comment by TrevorHansen** [comment]
Hi Mate, Outputs below!

[ec2-user@ip-172-31-4-202 ~]$ which c++/usr/bin/c++[ec2-user@ip-172-31-4-202 ~]$ ls -lah /usr/bin/c++lrwxrwxrwx 1 root root 21 Oct 13  2015 /usr/bin/c++ -> /etc/alternatives/c++[ec2-user@ip-172-31-4-202 ~]$ ls -lah /etc/alternatives/c++lrwxrwxrwx 1 root root 14 Oct 13  2015 /etc/alternatives/c++ -> /usr/bin/g++48[ec2-user@ip-172-31-4-202 ~]$ ls -lah /usr/bin/g++48-rwxr-xr-x 4 root root 740K Aug  6  2015 /usr/bin/g++48[ec2-user@ip-172-31-4-202 ~]$ c++ --versionc++ (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)Copyright (C) 2013 Free Software Foundation, Inc.This is free software; see the source for copying conditions.  There is NOwarranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[ec2-user@ip-172-31-4-202 ~]$ 

    On Thursday, 12 May 2016, 17:42, Mate Soos <notifications@github.com> wrote:
 
 

 Oh, and where c++ points to (which c++ then ls -lah [wherever c++ is]) and the version of the compiler it points to. e.g. gcc --version or clang --version. Thanks!—

**Comment by TrevorHansen** [comment]
It's Amazon linux, 
[ec2-user@ip-172-31-4-202 build]$ uname -r4.4.8-20.46.amzn1.x86_64


-- Doing a Release build-- The C compiler identification is GNU 4.8.3-- The CXX compiler identification is GNU 4.8.3-- Check for working C compiler: /usr/bin/cc-- Check for working C compiler: /usr/bin/cc -- works-- Detecting C compiler ABI info-- Detecting C compiler ABI info - done-- Check for working CXX compiler: /usr/bin/c++-- Check for working CXX compiler: /usr/bin/c++ -- works-- Detecting CXX compiler ABI info-- Detecting CXX compiler ABI info - done-- No pthread will be used-- Performing Test HAVE_FLAG_-Wall-- Performing Test HAVE_FLAG_-Wall - Success-- flag -Wall supported-- Performing Test HAVE_FLAG_-Wextra-- Performing Test HAVE_FLAG_-Wextra - Success-- flag -Wextra supported-- Performing Test HAVE_FLAG_-Wunused-- Performing Test HAVE_FLAG_-Wunused - Success-- flag -Wunused supported-- Performing Test HAVE_FLAG_-pedantic-- Performing Test HAVE_FLAG_-pedantic - Success-- flag -pedantic supported-- Performing Test HAVE_FLAG_-Wsign-compare-- Performing Test HAVE_FLAG_-Wsign-compare - Success-- flag -Wsign-compare supported-- Performing Test HAVE_FLAG_-Wtype-limits-- Performing Test HAVE_FLAG_-Wtype-limits - Success-- flag -Wtype-limits supported-- Performing Test HAVE_FLAG_-Wuninitialized-- Performing Test HAVE_FLAG_-Wuninitialized - Success-- flag -Wuninitialized supported-- Performing Test HAVE_FLAG_-Wno-deprecated-- Performing Test HAVE_FLAG_-Wno-deprecated - Success-- flag -Wno-deprecated supported-- Performing Test HAVE_FLAG_-Wstrict-aliasing-- Performing Test HAVE_FLAG_-Wstrict-aliasing - Success-- flag -Wstrict-aliasing supported-- Performing Test HAVE_FLAG_-Wpointer-arith-- Performing Test HAVE_FLAG_-Wpointer-arith - Success-- flag -Wpointer-arith supported-- Performing Test HAVE_FLAG_-Wheader-guard-- Performing Test HAVE_FLAG_-Wheader-guard - Failed-- flag -Wheader-guard NOT supported-- Performing Test HAVE_FLAG_-fvisibility=hidden-- Performing Test HAVE_FLAG_-fvisibility=hidden - Success-- flag -fvisibility=hidden supported-- flag -Wpointer-arith supported-- Performing Test HAVE_FLAG_-Wformat-nonliteral-- Performing Test HAVE_FLAG_-Wformat-nonliteral - Success-- flag -Wformat-nonliteral supported-- Performing Test HAVE_FLAG_-Winit-self-- Performing Test HAVE_FLAG_-Winit-self - Success-- flag -Winit-self supported-- Performing Test HAVE_FLAG_-Wparentheses-- Performing Test HAVE_FLAG_-Wparentheses - Success-- flag -Wparentheses supported-- Performing Test HAVE_FLAG_-Wunreachable-code-- Performing Test HAVE_FLAG_-Wunreachable-code - Success-- flag -Wunreachable-code supported-- Performing Test HAVE_FLAG_-ggdb3-- Performing Test HAVE_FLAG_-ggdb3 - Success-- flag -ggdb3 supported-- Compiling for static library use-- GIT hash found: 3c61248e1c974c37d392d8a5b1920c1d0e3fd5c5-- PROJECT_VERSION: 4.5.3-- PROJECT_VERSION_MAJOR: 4-- PROJECT_VERSION_MINOR: 5-- PROJECT_VERSION_PATCH: 3-- Looking for include file pthread.h-- Looking for include file pthread.h - found-- Looking for pthread_create-- Looking for pthread_create - not found-- Looking for pthread_create in pthreads-- Looking for pthread_create in pthreads - not found-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found-- Found Threads: TRUE-- Not compiling detailed statistics. Leads to faster system-- Valgrind Prefix:-- Could NOT find VALGRIND (missing:  VALGRIND_INCLUDE_DIR)-- Cannot find valgrind or it's disabled, we will not be able to mark memory pool objects as undefined-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")-- Found m4ri: /usr/local/lib/libm4ri.a-- OK, Found M4RI lib at /usr/local/lib/libm4ri.a and includes at /usr/local/include-- All defines at startup:  -DUSE_PTHREADS -DUSE_M4RI-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.10", minimum required is "2.7")-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES) (found suitable version "2.7.10", minimum required is "2.7")CMake Warning at CMakeLists.txt:380 (message):  Cannot find python interpreter, libs and header files -> not building  python plugin

-- Only building executable with few command-line options because the boost program_options library were not availableCMake Warning at CMakeLists.txt:440 (message):  Testing is disabled


-- Configuring done-- Generating done-- Build files have been written to: /home/ec2-user/stpcomp/cryptominisat/build



    On Thursday, 12 May 2016, 17:35, Mate Soos <notifications@github.com> wrote:
 
 

 Thanks! Can you please paste the output of the "cmake" command as well? (after rm -rf build) Also, can you please tell me what distribution you are running (e.g. Ubuntu 14.04)? Thanks!—

**Comment by msoos** [comment]
You were most probably missing these:

```
sudo yum -y groupinstall 'Development Tools'
sudo yum -y install boost-devel
sudo yum -y install cmake
sudo yum -y install zlib-devel
sudo yum -y install boost-static
sudo yum -y install libstdc++-static
sudo yum -y install glibc-static
```

Note in particular **the last last three**. I have launched an Amazon  AMI and the updated gist here:

https://gist.github.com/msoos/be2524d136132b96ef072ef7e2edf8a5

should work out of the box. Just execute as non-root (i.e. default ec2-user) and it will build a static STP executable.

I hope the above helps! Thanks a **lot** in advance for working on the SMT-LIB v2.5!

Mate

**Comment by TrevorHansen** [comment]
Hi Mate,

I'm getting a link error when I turn off simple_only. I.e. so I can get a static cryptominisat executable. Is this expected? My build config is:

cmake -DREQUIRE_M4RI=ON -DSTATICCOMPILE=ON -DENABLE_PYTHON_INTERFACE=OFF -DNOVALGRIND=ON -DNOZLIB=ON -DONLY_SIMPLE=OFF -DSTATICCOMPILE=ON -DCMAKE_BUILD_TYPE=Release ..

The output is:

Linking CXX executable ../cusp4
/usr/bin/ld: warning: unrecognized --build-id style ignored.
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_initialize_minimal':
(.text+0x177): undefined reference to `__libc_setup_tls'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_initialize_minimal':
(.text+0x1bc): undefined reference to `_dl_cpuclock_offset'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_initialize_minimal':
(.text+0x328): undefined reference to `__libc_init_secure'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_initialize_minimal':

**Comment by TrevorHansen** [comment]
Thanks for all your hardwork, it builds nicely now!! 

    On Friday, 13 May 2016, 8:18, Mate Soos <notifications@github.com> wrote:
 
 

 You were most probably missing these:sudo yum -y groupinstall 'Development Tools'
sudo yum -y install boost-devel
sudo yum -y install cmake
sudo yum -y install zlib-devel
sudo yum -y install boost-static
sudo yum -y install libstdc++-static
sudo yum -y install glibc-static
Note in particular the last last three. I have launched an Amazon AMI and the updated gist here:https://gist.github.com/msoos/be2524d136132b96ef072ef7e2edf8a5should work out of the box. Just execute as non-root (i.e. default ec2-user) and it will build a static STP executable.I hope the above helps! Thanks a lot in advance for working on the SMT-LIB v2.5!Mate—

**Comment by TrevorHansen** [comment]
I'd like to build a static CMS that I can specify the number of threads for. When I turn off simple_only, I get these linker errors:

Linking CXX executable ../cryptominisat4
/usr/bin/ld: warning: unrecognized --build-id style ignored.
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_initialize_minimal':
(.text+0x177): undefined reference to `__libc_setup_tls'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_initialize_minimal':
(.text+0x1bc): undefined reference to `_dl_cpuclock_offset'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_initialize_minimal':
(.text+0x328): undefined reference to `__libc_init_secure'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_initialize_minimal':
(.text+0x37a): undefined reference to `_dl_pagesize'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_initialize_minimal':
(.text+0x38b): undefined reference to `_dl_init_static_tls'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_initialize_minimal':
(.text+0x396): undefined reference to `_dl_wait_lookup_done'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__pthread_get_minstack':
(.text+0x463): undefined reference to `_dl_pagesize'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `pthread_create':
(.text+0x1872): undefined reference to `_dl_stack_flags'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `pthread_create':
(.text+0x2192): undefined reference to `_dl_stack_flags'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `pthread_getattr_np':
(.text+0x30bd): undefined reference to `_dl_pagesize'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `pthread_getattr_np':
(.text+0x3162): undefined reference to `_dl_pagesize'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__vfork':
(.text+0x7611): undefined reference to `__syscall_error'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__write_nocancel':
(.text+0x7638): undefined reference to `__syscall_error'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__write_nocancel':
(.text+0x766c): undefined reference to `__syscall_error'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__read_nocancel':
(.text+0x7698): undefined reference to `__syscall_error'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o): In function `__read_nocancel':
(.text+0x76cc): undefined reference to `__syscall_error'
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libpthread.a(libpthread.o):(.text+0x76f8): more undefined references to `__syscall_error' follow
collect2: error: ld returned 1 exit status
make[2]: *** [cryptominisat4] Error 1
make[1]: *** [cmsat4-src/CMakeFiles/cryptominisat4.dir/all] Error 2
make: *** [all] Error 2


Is it best to try and get this building, or to change the cryptominisat4_simple default parameters?

**Comment by TrevorHansen** [comment]
oops. Just saw the command line flags for _simple.. Withdraw the question..
